routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=> true]);

Route::group(['middleware' => ['admin']], function () {
    Route::resource('admin/users' , 'Admin\AdminUserController');
    Route::resource('admin/posts' , 'Admin\AdminPostController');
    Route::resource('admin/categories' , 'Admin\AdminCategoryController');
    Route::resource('admin/photos' , 'Admin\AdminPhotoController');
    Route::get('admin/dashboard' , 'Admin\AdminDashboardController@index')->name('admin.dashboard');
});
Route::get('/home', 'HomeController@index')->name('home');

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $uploads = '/images/';
    public function user()
    {
        return $this->belongsTo(User::class); //Each photo belongs to ONE user!
    }

    //Using Accessor for showing user avatar in admin index
    public function getPathAttribute($photo)
    {
        return $this->uploads . $photo;
    }
    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;


class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function photos()
    {
        return $this->hasMany(Photo::class); //Each User can have many photos
    }
    public function photo()
    {
        return $this->belongsTo(Photo::class); //this refers to users avatar
    }

    public function isAdmin()
    {
        foreach ($this->roles as $role)
            if ($role->name == 'مدیر' && $this->status == 1){
            return true;
            }
            return false;
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.master')

@section('content')
    <h3 class="p-b-2">افزودن کاربر</h3>
    <div class="row">
        <div class="col-md-6 offset-md-3">
            @include('partial.form-errors')
            {!! Form::open(['method' => 'POST', 'action' => 'Admin\AdminUserController@store', 'files'=> true]) !!}
            <div class="form-group">
                {!! Form::label('name','نام و نام خانوادگی:') !!}
                {!! Form::text('name', null ,['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('email','ایمیل:') !!}
                {!! Form::text('email', null ,['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('roles','نقش:') !!}
                {!! Form::select('roles[]', $roles, null , ['multiple'=>'multiple','class' =>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('status','وضعیت:') !!}
                {!! Form::select('status', [0=>'غیرفعال', 1=>'فعال'] , 0, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('avatar','تصویر پروفایل:') !!}
                {!! Form::file('avatar', null, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('password','رمز عبور:') !!}
                {!! Form::password('password', ['class' => 'form-control']) !!}
                {{--{!! Form::password('password', null, ['class' => 'form-control']) !!}--}}
            </div>
            <div class="form-group">
                {!! Form::submit('ذخیره', ['class' => 'btn btn-radius btn-success']) !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>



@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.master')

@section('content')
    <h3 class="p-b-2">ویرایش اطلاعات {{$user->name}}</h3>
    <div class="row">
        <div class="col-md-3">
            <img src="{{$user->photo ? $user->photo->path : "http://www.placehold.it/400"}}" class="img-fluid">
        </div>
        <div class="col-md-9">
            @include('partial.form-errors')
            {!! Form::model($user, ['method' => 'PATCH', 'action' => ['Admin\AdminUserController@update', $user->id], 'files'=> true]) !!}
            <div class="form-group">
                {!! Form::label('name','نام و نام خانوادگی:') !!}
                {!! Form::text('name', null ,['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('email','ایمیل:') !!}
                {!! Form::text('email', null ,['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('roles','نقش:') !!}
                {!! Form::select('roles[]', $roles, null , ['multiple'=>'multiple','class' =>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('status','وضعیت:') !!}
                {!! Form::select('status', [0=>'غیرفعال', 1=>'فعال'] , null, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('avatar','تصویر پروفایل:') !!}
                {!! Form::file('avatar', null, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('password','رمز عبور:') !!}
                {!! Form::password('password', ['class' => 'form-control']) !!}
                {{--{!! Form::password('password', null, ['class' => 'form-control']) !!}--}}
            </div>
            <div class="form-group">
                {!! Form::submit('بروزرسانی', ['class' => 'btn btn-radius btn-success']) !!}
            </div>
            {!! Form::close() !!}

            {{--Delete Form--}}
            {!! Form::open(['method' => 'DELETE', 'action' => ['Admin\AdminUserController@destroy', $user->id]]) !!}
                <div class="form-group">
                    {!! Form::submit('حذف', ['class' => 'btn btn-radius btn-danger']) !!}
                </div>
            {!! Form::close() !!}
            {{--Delete Form--}}
        </div>
    </div>



@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.master')

@section('content')
    @if(Session::has('delete_user'))
        <div class="alert alert-danger">
            <div>{{session('delete_user')}}</div>
        </div>
    @endif
    @if(Session::has('add_user'))
        <div class="alert alert-success">
            <div>{{session('add_user')}}</div>
        </div>
    @endif
    @if(Session::has('update_user'))
        <div class="alert alert-success">
            <div>{{session('update_user')}}</div>
        </div>
    @endif
    <h3 class="p-b-2">لیست کاربران</h3>
    <table class="table table-hover bg-content">
        <thead>
        <tr>
            <th>تصویر</th>
            <th>نام</th>
            <th>ایمیل</th>
            <th>نقش</th>
            <th>وضعیت</th>
            <th>تاریخ عضویت</th>
        </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
                <tr>
                    <td><img class="img-avatar" src="{{$user->photo ? $user->photo->path : "http://placehold.it/400*400"}}" width="80" alt="تصویر نمایه"></td>
                    <td><a href="{{route('users.edit', $user->id)}}">{{$user->name}}</a></td>
                    <td>{{$user->email}}</td>
                    <td>
                        <ul class="list-unstyled">
                            @foreach($user->roles as $role)
                                <li>{{$role->name}}</li>
                            @endforeach
                        </ul>
                    </td>
                    @if($user->status == 0)
                        <td><span class="tag tag-pill tag-danger">غیرفعال</span></td>
                        @else
                        <td><span class="tag tag-pill tag-success">فعال</span></td>
                    @endif
                    <td>{{Hekmatinasser\Verta\Verta::instance($user->created_at)->formatDifference(\Hekmatinasser\Verta\Verta::today('Asia/Tehran'))}}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="col-md-12 paginate-center">{{$users->links()}}</div>
@endsection