routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=> true]);

Route::group(['middleware' => ['admin']], function () {
    Route::resource('admin/users' , 'Admin\AdminUserController');
    Route::resource('admin/posts' , 'Admin\AdminPostController');
    Route::resource('admin/categories' , 'Admin\AdminCategoryController');
    Route::resource('admin/photos' , 'Admin\AdminPhotoController');
    Route::get('admin/dashboard' , 'Admin\AdminDashboardController@index')->name('admin.dashboard');
});
Route::get('/home', 'HomeController@index')->name('home');

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $uploads = '/images/';
    public function user()
    {
        return $this->belongsTo(User::class); //Each photo belongs to ONE user!
    }

    //Using Accessor for showing user avatar in admin index
    public function getPathAttribute($photo)
    {
        return $this->uploads . $photo;
    }
    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function photo()
    {
        return $this->belongsTo(Photo::class);
    }
}

resources/views/admin/posts/create.blade.php
@extends('admin.layouts.master')

@section('content')
    @include('partial.form-errors')
    <h3 class="p-b-2">افزودن مطلب جدید</h3>
    <div class="row">
        <div class="col-md-10 offset-md-1">
            {!! Form::open(['method' => 'POST', 'action' => 'Admin\AdminPostController@store', 'files'=> true]) !!}
            <div class="form-group">
                {!! Form::label('title','عنوان:') !!}
                {!! Form::text('title', null ,['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('slug','نام مستعار:') !!}
                {!! Form::text('slug', null ,['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('category','دسته بندی:') !!}
                {!! Form::select('category', $category ,null, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('description','توضیحات:') !!}
                {!! Form::textarea('description', null , ['class' =>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('meta_description','توضیحات متا:') !!}
                {!! Form::textarea('meta_description', null , ['class' =>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('featured_image','تصویر شاخص:') !!}
                {!! Form::file('featured_image', null, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('meta_keywords','کلمات کلیدی:') !!}
                {!! Form::textarea('meta_keywords', null , ['class' =>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('status','وضعیت:') !!}
                {!! Form::select('status', [0=>'پیش نویس', 1=>'منتشر شده'] , 0, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::submit('ذخیره', ['class' => 'btn btn-radius btn-success']) !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>



@endsection

resources/views/admin/posts/edit.blade.php
@extends('admin.layouts.master')

@section('content')
    <h3 class="p-b-2">ویرایش مطلب</h3>
    <div class="row">
        <div class="col-md-3">
            <img src="{{$post->photo ? $post->photo->path : "http://www.placehold.it/400"}}" class="img-fluid">
        </div>
        <div class="col-md-9">
            @include('partial.form-errors')
            {!! Form::model($post , ['method' => 'PATCH', 'action' => ['Admin\AdminPostController@update', $post->id], 'files'=> true]) !!}
            <div class="form-group">
                {!! Form::label('title','عنوان:') !!}
                {!! Form::text('title', null ,['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('slug','نام مستعار:') !!}
                {!! Form::text('slug', null ,['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('category','دسته بندی:') !!}
                {!! Form::select('category', $category , $post->category->id, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('description','توضیحات:') !!}
                {!! Form::textarea('description', null , ['class' =>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('meta_description','توضیحات متا:') !!}
                {!! Form::textarea('meta_description', null , ['class' =>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('featured_image','تصویر شاخص:') !!}
                {!! Form::file('featured_image', null, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('meta_keywords','کلمات کلیدی:') !!}
                {!! Form::textarea('meta_keywords', null , ['class' =>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('status','وضعیت:') !!}
                {!! Form::select('status', [0=>'پیش نویس', 1=>'منتشر شده'] , null, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::submit('بروزرسانی', ['class' => 'btn btn-radius btn-success']) !!}
            </div>
            {!! Form::close() !!}

            {{--Delete Form--}}
            {!! Form::open(['method' => 'DELETE', 'action' => ['Admin\AdminPostController@destroy', $post->id]]) !!}
                <div class="form-group">
                    {!! Form::submit('حذف', ['class' => 'btn btn-radius btn-danger']) !!}
                </div>
            {!! Form::close() !!}
            {{--Delete Form--}}
        </div>
    </div>



@endsection

resources/views/admin/posts/index.blade.php
@extends('admin.layouts.master')

@section('content')
    @if(Session::has('add_post'))
        <div class="alert alert-success">
            <div>{{session('add_post')}}</div>
        </div>
    @endif
    @if(Session::has('delete_post'))
        <div class="alert alert-danger">
            <div>{{session('delete_post')}}</div>
        </div>
    @endif
    @if(Session::has('update_post'))
        <div class="alert alert-success">
            <div>{{session('update_post')}}</div>
        </div>
    @endif
    <h3 class="p-b-2">لیست نوشته ها</h3>
    <table class="table table-hover bg-content">
        <thead>
        <tr>
            <th>تصویر</th>
            <th>عنوان</th>
            <th>توسط</th>
            <th>توضیحات</th>
            <th>دسته بندی</th>
            <th>وضعیت</th>
            <th>تاریخ ایجاد</th>
        </tr>
        </thead>
        <tbody>
            @foreach($posts as $post)
                <tr>
                    <td><img class="img-rounded" src="{{$post->photo ? $post->photo->path : "http://placehold.it/400*400"}}" width="80" alt="تصویر نمایه"></td>
                    <td><a href="{{route('posts.edit', $post->id)}}">{{$post->title}}</a></td>
                    <td>{{$post->user->name}}</td>
                    <td>{{str_limit($post->description , 100)}}</td>
                    <td>{{$post->category->title}}</td>
                    @if($post->status == 0)
                        <td><span class="tag tag-pill tag-danger">منتشر نشده</span></td>
                        @else
                        <td><span class="tag tag-pill tag-success">منتشر شده</span></td>
                    @endif
                    <td>{{Hekmatinasser\Verta\Verta::instance($post->created_at)->formatDifference(\Hekmatinasser\Verta\Verta::today('Asia/Tehran'))}}</td>
                </tr>
            @endforeach
        </tbody>
    </table>


@endsection