routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify'=> true]);

Route::group(['middleware' => ['admin']], function () {
    Route::resource('admin/users' , 'Admin\AdminUserController');
    Route::resource('admin/posts' , 'Admin\AdminPostController');
    Route::resource('admin/categories' , 'Admin\AdminCategoryController');
    Route::resource('admin/photos' , 'Admin\AdminPhotoController');
    Route::get('admin/dashboard' , 'Admin\AdminDashboardController@index')->name('admin.dashboard');
});
Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')

@section('content')
    @include('partial.form-errors')
    <h3 class="p-b-2">افزودن دسته جدید</h3>
    <div class="row">
        <div class="col-md-6 offset-md-3">
            {!! Form::open(['method' => 'POST', 'action' => 'Admin\AdminCategoryController@store']) !!}
            <div class="form-group">
                {!! Form::label('title','عنوان:') !!}
                {!! Form::text('title', null ,['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('slug','نام مستعار:') !!}
                {!! Form::text('slug', null ,['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('meta_description','توضیحات متا:') !!}
                {!! Form::textarea('meta_description', null , ['class' =>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('meta_keywords','کلمات کلیدی:') !!}
                {!! Form::textarea('meta_keywords', null , ['class' =>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::submit('ذخیره', ['class' => 'btn btn-radius btn-success']) !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')

@section('content')
    @include('partial.form-errors')
    <h3 class="p-b-2">ویرایش دسته</h3>
    <div class="row">
        <div class="col-md-6 offset-md-3">
            {!! Form::model($category, ['method' => 'PATCH', 'action' => ['Admin\AdminCategoryController@update', $category->id]]) !!}
            <div class="form-group">
                {!! Form::label('title','عنوان:') !!}
                {!! Form::text('title', null ,['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('slug','نام مستعار:') !!}
                {!! Form::text('slug', null ,['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('meta_description','توضیحات متا:') !!}
                {!! Form::textarea('meta_description', null , ['class' =>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('meta_keywords','کلمات کلیدی:') !!}
                {!! Form::textarea('meta_keywords', null , ['class' =>'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::submit('بروزرسانی', ['class' => 'btn btn-radius btn-success']) !!}
            </div>
            {!! Form::close() !!}
            {{--Delete Form--}}
            {!! Form::open(['method' => 'DELETE', 'action' => ['Admin\AdminCategoryController@destroy', $category->id]]) !!}
            <div class="form-group">
                {!! Form::submit('حذف', ['class' => 'btn btn-radius btn-danger']) !!}
            </div>
            {!! Form::close() !!}
            {{--Delete Form--}}
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master')

@section('content')
    @if(Session::has('add_category'))
        <div class="alert alert-success">
            <div>{{session('add_category')}}</div>
        </div>
    @endif
    @if(Session::has('delete_category'))
        <div class="alert alert-danger">
            <div>{{session('delete_category')}}</div>
        </div>
    @endif
    @if(Session::has('update_category'))
        <div class="alert alert-success">
            <div>{{session('update_category')}}</div>
        </div>
    @endif
    <h3 class="p-b-2">لیست دسته ها</h3>
    <table class="table table-hover bg-content">
        <thead>
        <tr>
            <th>شناسه</th>
            <th>عنوان دسته</th>
            <th>تاریخ ایجاد</th>
        </tr>
        </thead>
        <tbody>
            @foreach($categories as $category)
                <tr>
                    <td><a href="{{route('categories.edit', $category->id)}}">{{$category->id}}</a></td>
                    <td>{{$category->title}}</td>
                    <td>{{Hekmatinasser\Verta\Verta::instance($category->created_at)->formatDifference(\Hekmatinasser\Verta\Verta::today('Asia/Tehran'))}}</td>
                </tr>
            @endforeach
        </tbody>
    </table>


@endsection